
@section('title', 'dwrite.me | Write For Human')
@section('meta_description', 'dwrite.me is a dedicated digital space engineered to filter out synthetic noise, ensuring a pure and focused human reading experience.')

<x-home-layout>
    <div class="max-w-5xl px-6 pt-20 md:pt-32 pb-20 mx-auto overflow-hidden">
        <header class="text-center relative">        
            <div class="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-24 w-[600px] h-[600px] bg-gray-50 rounded-full blur-[120px] -z-10 opacity-60"></div>
    
            <div class="inline-block px-4 py-1.5 mb-8 rounded-full bg-gray-50 border border-gray-100 shadow-sm">
                <span class="text-[10px] font-black uppercase tracking-[0.4em] text-black">dwrite.me</span>
            </div>
    
            <h1 class="text-4xl md:text-[110px] font-black tracking-[-0.06em] leading-[0.9] md:leading-[0.85] mb-12 text-[#1a1a1a] lowercase">
                write for <span class="relative inline-block mt-2 md:mt-0 px-3 md:px-5 py-0 md:py-1 bg-[#1a1a1a] text-white rounded-xl md:rounded-xl">
                    human.
                </span>
            </h1>
        
            <p class="text-[18px] md:text-[22px] text-gray-400 font-light mb-20 max-w-xl mx-auto leading-relaxed">
                Every keystroke is a <span class="text-black font-bold italic">conscious decision.</span> <br> 
                Because your mind is not an algorithm.
            </p>
        
            <div class="flex flex-col items-center gap-10">
                <div class="relative group">
                    <div class="absolute inset-0 bg-black rounded-full blur-xl opacity-5 group-hover:opacity-10 transition-opacity"></div>
                    
                    <a href="#start" class="relative flex items-center gap-3 px-8 py-4 bg-[#1a1a1a] text-white rounded-full">
                        <span class="text-[15px] font-black">Begin your story</span>
                        
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3.5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                        </svg>
                    </a>
                </div>
            </div>
        </header>
    </div>
    
    <div class="max-w-3xl mx-auto pt-24 px-6">
        <div class="space-y-32">
            <section id="about" class="fade-in opacity-0">
                <h2 class="text-3xl font-bold tracking-tight mb-8 text-[#1a1a1a]">What is this?</h2>
                <div class="text-xl md:text-2xl text-gray-600 space-y-8 font-light leading-relaxed">
                    <p>
                        dwrite.me is a specialized digital environment designed to eliminate synthetic noise. We operate on a single, non-negotiable protocol: 
                        <span class="font-semibold text-black underline underline-offset-8 decoration-1">every character must be typed manually.</span>
                    </p>
                    <p>
                        By hard-coding the exclusion of the paste function and prohibiting AI integration, we ensure that this platform remains a zero-synthetic zone. Every article you read here is a verified artifact of human cognition, executed in real-time, letter by letter.
                    </p>
                </div>
            </section>

            <section id="data" class="fade-in opacity-0 pt-16 border-t border-gray-100">
                <h2 class="text-3xl font-bold tracking-tight mb-10 text-[#1a1a1a]">The Synthetic Flood</h2>
                <div class="text-xl md:text-2xl text-gray-600 space-y-8 font-light leading-relaxed">
                    <p>
                        Current industry data indicates that approximately <span class="font-semibold text-black">10% to 20% of new internet content</span> is generated by Artificial Intelligence. Projections from Europol suggest this figure will reach <span class="font-semibold text-black">90% by 2026.</span>
                    </p>
                    <p>
                        This automation serves a recursive loop: AI generates text to manipulate search engine algorithms, while automated bots consume and summarize that data to train subsequent models. Consuming synthetic content offers no intellectual value; it is a feedback loop of statistical patterns designed for machines, not for human connection.
                    </p>
                </div>
            </section>

            <section id="manifesto" class="fade-in opacity-0 pt-4 border-t border-gray-100">
                <h2 class="text-3xl font-bold tracking-tight mb-10 text-[#1a1a1a]">Why it matters</h2>
                <ul class="space-y-12">
                    <li class="flex gap-6">
                        <span class="text-gray-300 font-light text-3xl">—</span>
                        <p class="text-xl md:text-2xl text-gray-600 font-light leading-relaxed">
                            <strong class="font-bold text-black">Proof of Human Presence</strong> – In an era of automated text, manual typing is the only definitive proof that a biological mind is behind the words.
                        </p>
                    </li>
                    <li class="flex gap-6">
                        <span class="text-gray-300 font-light text-3xl">—</span>
                        <p class="text-xl md:text-2xl text-gray-600 font-light leading-relaxed">
                            <strong class="font-bold text-black">Cognitive Resistance</strong> – AI optimizes for the average; handcrafted writing preserves the "noise," imperfections, and erratic rhythms that define genuine human intelligence.
                        </p>
                    </li>
                    <li class="flex gap-6">
                        <span class="text-gray-300 font-light text-3xl">—</span>
                        <p class="text-xl md:text-2xl text-gray-600 font-light leading-relaxed">
                            <strong class="font-bold text-black">Anti-Algorithmic Integrity</strong> – By disabling the paste function, we prevent the injection of synthetic data, ensuring that every thought is processed and verified by a human nervous system before it is published.
                        </p>
                    </li>
                </ul>
            </section>

            <section id="essence" class="fade-in opacity-0 pt-16 border-t border-gray-100">
                <div class="grid grid-cols-1 md:grid-cols-3 gap-12 text-center md:text-left">
                    <div>
                        <h3 class="text-[11px] font-black uppercase tracking-[0.3em] text-gray-300 mb-4">The Logic</h3>
                        <p class="text-2xl font-bold text-[#1a1a1a] tracking-tight">Simple as default.</p>
                        <p class="text-gray-500 mt-2 font-light">Eliminating every unnecessary feature to focus on the raw act of creation.</p>
                    </div>
                    <div>
                        <h3 class="text-[11px] font-black uppercase tracking-[0.3em] text-gray-300 mb-4">The Vision</h3>
                        <p class="text-2xl font-bold text-[#1a1a1a] tracking-tight">Free as intention.</p>
                        <p class="text-gray-500 mt-2 font-light">Liberating thoughts from algorithms, predictive text, and synthetic echoes.</p>
                    </div>
                    <div>
                        <h3 class="text-[11px] font-black uppercase tracking-[0.3em] text-gray-300 mb-4">The Result</h3>
                        <p class="text-2xl font-bold text-[#1a1a1a] tracking-tight">Pure as human.</p>
                        <p class="text-gray-500 mt-2 font-light">A verified record of what it actually feels like to think and type in real-time.</p>
                    </div>
                </div>
            </section>

            <section id="start" class="fade-in opacity-0 pt-16 border-t border-gray-100 text-center pb-32">
                <h2 class="text-4xl font-bold tracking-tight mb-8 text-[#1a1a1a]">Ready to write?</h2>
                <p class="text-xl md:text-2xl text-gray-500 font-light mb-12 max-w-lg mx-auto leading-relaxed">
                    Join others who believe writing should be an act of thinking, not just producing data.
                </p>
                <div class="flex flex-col sm:flex-row justify-center gap-6">
                    <a href="{{ route('dashboard') }}" class="px-10 py-4 font-bold bg-[#1a1a1a] text-white rounded-full hover:bg-black transition shadow-xl shadow-black/10 text-base md:text-lg">Start writing now</a>
                    <a href="{{ route('articles.index') }}" class="px-10 py-4 font-bold bg-white text-[#1a1a1a] border border-gray-200 rounded-full hover:bg-gray-50 transition text-base md:text-lg">Read feed</a>
                </div>
            </section>
        </div>
    </div>

    <script>
        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('fade-in');
                    entry.target.style.opacity = '1';
                }
            });
        }, { threshold: 0.1 });
        
        document.querySelectorAll('section').forEach(section => {
            observer.observe(section);
        });
    </script>
</x-home-layout>